### ISSUE TITLE
Add repository to Packagist

### ISSUE THREAD

**Issue by mrohnstock** [components/jquery-migrate#1]
@RobLoach could you please add this repo to packagist? I'm unable to do this, as I'm not the owner of the vendor `components`, as packagist mention:

```
The vendor is already taken by someone else. You may ask them to add your package and give you maintainership access. The packages already in that vendor namespace can be found at components
```

**Comment by RobLoach** [comment]
You're a maintainer on there now too https://packagist.org/packages/components/jquery-migrate

**Comment by RobLoach** [comment]
Thanks for adding this!
